lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "click"
version = "8.1.7"

[[packages.wheels]]
name = "click-8.1.7-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "ae74fb96c20a0277a1d615f1e4d73c8414f5a98db8b799a7931d1582f3390c28"

[[packages]]
name = "dep-2"

[packages.directory]
path = "."
